# General
name: TouchUp
tagline: Nettoyez et améliorez vos contacts en vous amusant

# Jekyll
exclude: ['Rakefile']
markdown: redcarpet

# App Store
appstore_url: https://itunes.apple.com/app/id1128944336
appstore: <a href="https://itunes.apple.com/app/id1128944336" class="app-store" rel="external nofollow"><img src="/assets/app-store.svg" alt="Download on the App Store"></a>
appstore_white: <a href="https://itunes.apple.com/app/id1128944336" class="app-store" rel="external nofollow"><img src="/assets/download_appstore_badge.svg" alt="Download on the App Store"></a>

# Screenshots
screenshots:
- screenshot01
- screenshot02
- screenshot03
- screenshot04
- screenshot05


# Company Info
company: TouchUp
company_website: https://touchupcontacts.github.io

# Emails
email_press: press@appname.com
email_contact: contact@appname.com
email_support: support@appname.com
